In [2]:
import pandas as pd
import numpy as np
from IPython.display import display
from fastai.imports import *
from sklearn import metrics
from pandas.tseries.offsets import DateOffset
import matplotlib.pyplot as plt

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

hour_ahead = 24
n_estimators = 80
learning_rate = 0.1
Depth = 8
Min_leaf = 1
Top = 30

path = "/content/drive/MyDrive/Colab Notebooks/Project/30.csv"
Merge_all = pd.read_csv(path)
dti = pd.to_datetime(Merge_all['DateTime'], format='%m/%d/%Y %H', exact=False)
Merge_all.set_index(pd.Index(dti), inplace=True)
Merge_all.drop(['DateTime'], axis=1, inplace=True)

First = Merge_all.iloc[0:11000, :]
N_index = First.shape
Y_temp = First['FI']
Y = Y_temp.iloc[hour_ahead:N_index[0]]
#Y.reset_index(drop=True, inplace=True)
#Y.columns = [''] * len(Y.columns)


X_temp1 = First['FI']
X_temp2 = First.loc[:, First.columns != 'FI']
X_temp2_index = X_temp2.index + DateOffset(hours=-hour_ahead)
X_temp2.set_index(X_temp2_index, inplace=True)
X_temp1 = X_temp1.to_frame()
X_temp = X_temp1.join(X_temp2)
X = X_temp.iloc[0:N_index[0] - hour_ahead]

#X.reset_index(drop=True, inplace=True)
#X.columns = [''] * len(X.columns)
Pred_index = X.shape
print("Shape = "+str(Pred_index))

from sklearn.linear_model import LinearRegression
model2 = LinearRegression()
model2.fit(X, Y)
importance2 = model2.coef_
FeatureR = []
FeatureR_index = X.columns
for i,v in enumerate(importance2):
    FeatureR.append(v)

Yfri = pd.DataFrame({'Index':FeatureR_index})
Yfr = pd.DataFrame({'Y':FeatureR})
Yfr.index = Yfri['Index']
Yfr.sort_values(by=['Y'], inplace=True)




TopIndex = Yfr.index[(789-Top):789] 
Merge_all.drop(Merge_all.columns.difference(TopIndex), axis=1, inplace=True)



Pred_index = Merge_all.shape
print("Shape = "+str(Pred_index))
print(Merge_all)
Merge_all.to_csv("/content/drive/MyDrive/Colab Notebooks/Project/star_data_set.csv")

Shape = (10976, 789)
Shape = (74496, 30)
                        FI  3_Precipitation amount (mm)  ...  Quarter  Working_Time
DateTime                                                 ...
2013-01-01 00:00:00  31.04                     0.190783  ...        1             0
2013-01-01 01:00:00  27.51                     1.280630  ...        1             0
2013-01-01 02:00:00  24.44                    -0.453963  ...        1             0
2013-01-01 03:00:00  21.81                     0.577589  ...        1             0
2013-01-01 04:00:00  22.37                     0.425256  ...        1             0
...                    ...                          ...  ...      ...           ...
NaT                    NaN                          NaN  ...        2             0
NaT                    NaN                          NaN  ...        2             0
NaT                    NaN                          NaN  ...        2             0
NaT                    NaN                          NaN  ...        2             0
NaT                    NaN                          NaN  ...        2             0

[74496 rows x 30 columns]